[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
rug = "1.18.0"
anyhow = "1.0.67"
lazy_static = "1.4.0"
